server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fab_todo_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "060720"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 2793864053@qq.com
    password: ejcmqrirzosddhce
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: FabTodoSecretKeyForJWT2024MustBeAtLeast256BitsLong!@#$%^
  expiration: 86400000
