CREATE DATABASE IF NOT EXISTS fab_todo_db
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE fab_todo_db;

CREATE TABLE IF NOT EXISTS fab_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) DEFAULT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    status INT NOT NULL DEFAULT 1 COMMENT '0=禁用, 1=启用',
    qq VARCHAR(20) DEFAULT NULL COMMENT 'QQ 号',
    nickname VARCHAR(50) DEFAULT NULL COMMENT '用户昵称',
    email_change_count INT NOT NULL DEFAULT 0 COMMENT '当天修改邮箱次数',
    email_change_date DATE DEFAULT NULL COMMENT '最近一次修改邮箱的日期',
    last_notice_seen_at DATETIME DEFAULT NULL COMMENT '最近一次查看公告的时间',
    force_logout_at DATETIME DEFAULT NULL COMMENT '强制下线时间',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_username (username),
    INDEX idx_role (role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fab_todo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    level VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW/MEDIUM/HIGH',
    deadline DATETIME DEFAULT NULL,
    done INT NOT NULL DEFAULT 0 COMMENT '0=未完成, 1=已完成',
    reminded INT NOT NULL DEFAULT 0 COMMENT '0=未提醒, 1=已提醒',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id),
    INDEX idx_deadline (deadline),
    INDEX idx_reminded (reminded),
    CONSTRAINT fk_todo_user FOREIGN KEY (user_id) REFERENCES fab_user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fab_notice (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
